// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/task_list.proto

/*
Package tasklistgateway is a generated protocol buffer package.

It is generated from these files:
	proto/task_list.proto

It has these top-level messages:
	Task
	GetTaskRequest
*/
package tasklistgateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Id     int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Detail string `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type GetTaskRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetTaskRequest) Reset()                    { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()               {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetTaskRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Task)(nil), "tasklistgateway.Task")
	proto.RegisterType((*GetTaskRequest)(nil), "tasklistgateway.GetTaskRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TaskManager service

type TaskManagerClient interface {
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (TaskManager_ListTasksClient, error)
}

type taskManagerClient struct {
	cc *grpc.ClientConn
}

func NewTaskManagerClient(cc *grpc.ClientConn) TaskManagerClient {
	return &taskManagerClient{cc}
}

func (c *taskManagerClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := grpc.Invoke(ctx, "/tasklistgateway.TaskManager/GetTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskManagerClient) ListTasks(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (TaskManager_ListTasksClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TaskManager_serviceDesc.Streams[0], c.cc, "/tasklistgateway.TaskManager/ListTasks", opts...)
	if err != nil {
		return nil, err
	}
	x := &taskManagerListTasksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaskManager_ListTasksClient interface {
	Recv() (*Task, error)
	grpc.ClientStream
}

type taskManagerListTasksClient struct {
	grpc.ClientStream
}

func (x *taskManagerListTasksClient) Recv() (*Task, error) {
	m := new(Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TaskManager service

type TaskManagerServer interface {
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	ListTasks(*google_protobuf.Empty, TaskManager_ListTasksServer) error
}

func RegisterTaskManagerServer(s *grpc.Server, srv TaskManagerServer) {
	s.RegisterService(&_TaskManager_serviceDesc, srv)
}

func _TaskManager_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskManagerServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tasklistgateway.TaskManager/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskManagerServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskManager_ListTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskManagerServer).ListTasks(m, &taskManagerListTasksServer{stream})
}

type TaskManager_ListTasksServer interface {
	Send(*Task) error
	grpc.ServerStream
}

type taskManagerListTasksServer struct {
	grpc.ServerStream
}

func (x *taskManagerListTasksServer) Send(m *Task) error {
	return x.ServerStream.SendMsg(m)
}

var _TaskManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tasklistgateway.TaskManager",
	HandlerType: (*TaskManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _TaskManager_GetTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListTasks",
			Handler:       _TaskManager_ListTasks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/task_list.proto",
}

func init() { proto.RegisterFile("proto/task_list.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x99, 0x68, 0x2b, 0x1d, 0xa1, 0xc2, 0xc5, 0x96, 0x1a, 0xa5, 0x86, 0xe8, 0xa2, 0x16,
	0x9c, 0xf1, 0x67, 0xd7, 0xb5, 0xe2, 0x46, 0x37, 0xc1, 0xbd, 0xdc, 0x90, 0x31, 0x0c, 0x8d, 0x99,
	0xd8, 0xb9, 0x55, 0x8a, 0xb8, 0xf1, 0x15, 0x7c, 0x34, 0x1f, 0xc0, 0x8d, 0x0f, 0x22, 0x33, 0x49,
	0x17, 0x56, 0xba, 0x3c, 0xf7, 0x9c, 0xf9, 0x0e, 0x73, 0x78, 0xaf, 0x9a, 0x19, 0x32, 0x92, 0xd0,
	0x4e, 0x1f, 0x0a, 0x6d, 0x49, 0x78, 0x0d, 0x3b, 0xee, 0xe0, 0x74, 0x8e, 0xa4, 0x5e, 0x71, 0x11,
	0xee, 0xe7, 0xc6, 0xe4, 0x85, 0x92, 0xde, 0x4e, 0xe7, 0x8f, 0x52, 0x3d, 0x55, 0xb4, 0xa8, 0xd3,
	0xe1, 0x41, 0x63, 0x62, 0xa5, 0x25, 0x96, 0xa5, 0x21, 0x24, 0x6d, 0x4a, 0x5b, 0xbb, 0xf1, 0x15,
	0xdf, 0xbc, 0x47, 0x3b, 0x85, 0x2e, 0x0f, 0x74, 0x36, 0x60, 0x11, 0x1b, 0xb5, 0x92, 0x40, 0x67,
	0xb0, 0xcb, 0x5b, 0xa4, 0xa9, 0x50, 0x83, 0x20, 0x62, 0xa3, 0x4e, 0x52, 0x0b, 0xe8, 0xf3, 0x76,
	0xa6, 0x08, 0x75, 0x31, 0xd8, 0xf0, 0xe7, 0x46, 0xc5, 0x11, 0xef, 0xde, 0x28, 0x72, 0xa0, 0x44,
	0x3d, 0xcf, 0x95, 0xa5, 0x55, 0xde, 0xc5, 0x37, 0xe3, 0xdb, 0xce, 0xbf, 0xc3, 0x12, 0x73, 0x35,
	0x83, 0x82, 0x6f, 0x35, 0x2f, 0xe0, 0x50, 0xac, 0xfc, 0x47, 0xfc, 0x65, 0x85, 0xbd, 0x7f, 0x01,
	0xe7, 0xc6, 0x27, 0x1f, 0x5f, 0x3f, 0x9f, 0xc1, 0x11, 0x0c, 0xe5, 0xcb, 0xb9, 0x5c, 0x26, 0x4e,
	0x9b, 0x88, 0x3f, 0xc8, 0x37, 0x9d, 0xbd, 0x4f, 0xd8, 0x18, 0x52, 0xde, 0xb9, 0xd5, 0xd6, 0x43,
	0x2d, 0xf4, 0x45, 0xbd, 0x88, 0x58, 0xce, 0x25, 0xae, 0xdd, 0x5c, 0xeb, 0x6a, 0x8e, 0x7d, 0xcd,
	0x10, 0xf6, 0xd6, 0xd6, 0x4c, 0xd8, 0xf8, 0x8c, 0xa5, 0x6d, 0x8f, 0xbb, 0xfc, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x27, 0x62, 0x97, 0xb5, 0xb5, 0x01, 0x00, 0x00,
}
